spring:
  sql:
    init:
      mode: always

  mail:
    host: ${MAIL_HOST:smtp.eu.mailgun.org}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    test-connection: true

discord:
  token: ${DISCORD_TOKEN}
  guild: ${DISCORD_GUILD:760863954607669269}
  confirmation-channel: ${DISCORD_CONFIRMATION_CHANNEL:1018219048028340284}
  verified-role: ${DISCORD_VERIFIED_ROLE:799326721530003546}