drop table if exists pending_verifications;

create table pending_verifications
(
    id       int         not null generated by default as identity primary key,
    username varchar(8)  not null unique,
    code     varchar(32) not null unique
);
